name: 'tagger'
description: 'generates tags based on environment variables created by hashibuto/actions/version'
inputs:
  create-version-tag:
    description: 'create a version tag if the current branch is the parent branch'
    type: 'boolean'
    default: 'false'
  create-major-version-tag:
    description: 'create a major version tag if the current branch is the parent branch'
    type: 'boolean'
    default: 'false'
  update-base-tag:
    description: 'update the base tag when using in conjunction with hashibuto/actions/change-matrix (runs at the end of all jobs on merge)'
    type: 'boolean'
    default: 'false'
  parent-branch:
    description: 'parent branch'
    required: false
  base-tag:
    default: 'change-base'
  github-token:
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
